CREATE DATABASE DEMO;
USE DEMO;

CREATE TABLE PRODUCTS
(
    ID                 INT PRIMARY KEY NOT NULL,
    PRODUCTCODE        VARCHAR(20)     NOT NULL,
    PRODUCTNAME        VARCHAR(30)     NOT NULL,
    PRODUCTPRICE       INT,
    PRODUCTAMOUNT      INT,
    PRODUCTDESCRIPTION VARCHAR(1000),
    PRODUCTSTATUS      BIT
);

INSERT INTO PRODUCTS
VALUES (1, 'SP01', 'HP 348 G7', 1000, 10, 'BLACK', 1),
       (2, 'SP02', 'Asus VivoBook X441MA', 5500, 20, 'RED', 1),
       (3, 'SP03', 'HP 348 G7', 3000, 3, 'BLUE', 0),
       (4, 'SP03A', 'Lenovo IdeaPad Slim 3 15IIL05', 3123, 12, 'RED', 1),
       (5, 'SP03B', 'Asus VivoBook X409JA ', 1234, 39, 'WHITE', 0),
       (6, 'SP04', 'Dell Vostro 3580', 2534, 52, 'YELLOW', 1),
       (7, 'SP05', 'HP 348 G7', 1003, 12, 'GREEN', 1),
       (8, 'SP06', 'Dell Inspiron 3493', 7832, 32, 'BLACK', 1),
       (9, 'SP07', 'HP 15s du1076TX', 4532, 75, 'BLUE', 1),
       (10, 'SP07A', 'Dell Inspiron 5593', 9345, 35, 'RED', 0),
       (11, 'SP08', 'Dell Vostro 5581', 7354, 43, 'PINK', 1),
       (12, 'SP009', 'Dell Inspiron 3581', 1238, 13, 'RED', 1),
       (13, 'SP010', 'Dell Vostro 3491', 7834, 86, 'BLACK', 1),
       (14, 'SP011', 'HP Pavilion x360 dh0103TU', 3541, 23, 'GREEN', 0),
       (15, 'SP012', 'Asus VivoBook A412FA', 5343, 46, 'RED', 1),
       (16, 'SP012A', 'HP Pavilion 15 cs3010TU', 7834, 83, 'WHITE', 1),
       (17, 'SP012B', 'Asus VivoBook A512FA', 4561, 81, 'BLACK', 0),
       (18, 'SP012C', 'Lenovo Ideapad S145 15IWL', 4536, 64, 'BLUE', 1),
       (19, 'SP013', 'HP Pavilion x360 14 dw0060TU', 1237, 94, 'GREEN', 0),
       (20, 'SP014', 'Lenovo IdeaPad S340 14IIL', 7843, 28, 'WHITE', 1);

ALTER TABLE PRODUCTS
    ADD UNIQUE INDEX idx_product_code (PRODUCTCODE);

ALTER TABLE PRODUCTS
    ADD INDEX idx_product_name_and_price (PRODUCTNAME, PRODUCTPRICE);

EXPLAIN
SELECT *
FROM PRODUCTS
WHERE PRODUCTCODE = 'SP012';

EXPLAIN
SELECT *
FROM PRODUCTS
WHERE PRODUCTNAME LIKE 'HP%'
  AND PRODUCTPRICE < 3000;

ALTER VIEW PRODUCTINFO AS
    SELECT PRODUCTCODE, PRODUCTNAME, PRODUCTPRICE, PRODUCTSTATUS
    FROM PRODUCTS;

SELECT *
FROM PRODUCTINFO;

ALTER VIEW PRODUCTINFO AS
    SELECT *
    FROM PRODUCTS;

DROP VIEW productinfo;

DELIMITER //
CREATE PROCEDURE GETPRODUCTINFO()
BEGIN
    SELECT * FROM PRODUCTS;
END //
DELIMITER ;

CALL GETPRODUCTINFO();

DELIMITER //
CREATE PROCEDURE ADDPRODUCT(IN ID INT,
                            IN PRODUCTCODE VARCHAR(20),
                            IN PRODUCTNAME VARCHAR(30),
                            IN PRODUCTPRICE INT,
                            IN PRODUCTAMOUNT INT,
                            IN PRODUCTDESCRIPTION VARCHAR(1000),
                            IN PRODUCTSTATUS BIT)
BEGIN
    INSERT INTO PRODUCTS
        VALUE (ID,
               PRODUCTCODE,
               PRODUCTNAME,
               PRODUCTPRICE,
               PRODUCTAMOUNT,
               PRODUCTDESCRIPTION,
               PRODUCTSTATUS);
END //
DELIMITER ;

CALL ADDPRODUCT(99, 'SP99', 'Acer Aspire E5', 9999, 1, 'LIGHT BLUE', 1);

DELIMITER //
CREATE PROCEDURE EDITPRODUCT(IN PRODUCTID INT,
                             IN NEWPRODUCTCODE VARCHAR(20),
                             IN NEWPRODUCTNAME VARCHAR(30),
                             IN NEWPRODUCTPRICE INT,
                             IN NEWPRODUCTAMOUNT INT,
                             IN NEWPRODUCTDESCRIPTION VARCHAR(1000),
                             IN NEWPRODUCTSTATUS BIT)
BEGIN
    UPDATE PRODUCTS
    SET PRODUCTCODE        = NEWPRODUCTCODE,
        PRODUCTNAME        = NEWPRODUCTNAME,
        PRODUCTPRICE       = NEWPRODUCTPRICE,
        PRODUCTAMOUNT      = NEWPRODUCTAMOUNT,
        PRODUCTDESCRIPTION = NEWPRODUCTDESCRIPTION,
        PRODUCTSTATUS      = NEWPRODUCTSTATUS
    WHERE ID = PRODUCTID;
END //
DELIMITER ;

CALL EDITPRODUCT(9, 'SP9ADC', 'Dell Inspiron 7501 X3MRY1', 5555, 0, 'BLACK', 1);

DELIMITER //
CREATE PROCEDURE DELETEPRODUCT(IN PRODUCTID INT)
BEGIN
    DELETE FROM PRODUCTS WHERE ID = PRODUCTID;
END //
DELIMITER ;

CALL DELETEPRODUCT(3);
